### PR TITLE
Sed 1306 ts   full interactive analysis based on raw measurements

### PR DESCRIPTION
**Pull request by lucianbaciu**

### CODE REVIEW

**Review by david-stephan — COMMENTED** [review]
In addition to inline comments, please add new junit test for RAW measurements, OQL validation....

**Comment by lucianbaciu** [comment]
@david-stephan regarding the tests, can you point me to a place where we test the endpoints, so I can follow?

**Comment by david-stephan** [comment]
@lucianbaciu for junit related to endpoints, I have no location to share since in Step we usually avoid having much logic directly in the endpoint and test them e2e. Still it's doable just pass the context in a new constructor or give it a try with the Jersey test framework.

**Review by david-stephan — CHANGES_REQUESTED** [review]
@lucianbaciu minor changes requested for the TimeSeriesHandler class

**Comment by lucianbaciu** [comment]
I decided to not add Configuration object in the Handler, and pass the direct params instead

**Review by david-stephan — DISMISSED** [review]
BE code change approved, some FE changes pending to be approved. We'll only merge to master  when all checks passed.

**Review by david-stephan — APPROVED** [review]

**Pull request merged**
